import Head from "next/head";
import { useEffect, useState } from "react";
import Item from "../components/Item";

export default function Home() {
  const [selectedItems, setSelectedItems] = useState([]);
  const [items, setItems] = useState([]);

  const isItemSelected = (itemId) => selectedItems.includes(itemId);
  const selectItem = (itemId) => {
    return [...selectedItems, itemId];
  };
  const deselectItem = (itemId) => {
    return selectedItems.filter((x) => x !== itemId);
  };
  const handleClick = (itemId) => (event) => {
    if (isItemSelected(itemId)) {
      setSelectedItems(deselectItem(itemId));
      return;
    }

    setSelectedItems(selectItem(itemId));
  };
  const itemBtnValue = (itemId) => {
    if (isItemSelected(itemId)) {
      return "➖ Remove from cart";
    }
    return "➕ Add to cart";
  };
  const itemBtnColor = (itemId) => {
    if (isItemSelected(itemId)) {
      return "btn btn-danger";
    }
    return "btn btn-success";
  };
  const handleSubmit = (event) => {
    event.preventDefault();

    const requestOptions = {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(selectedItems),
    };
    fetch("/api/checkout", requestOptions)
      .then((response) => response.json())
      .then((res) => console.log(res));
  };

  useEffect(() => {
    fetch("/api/items")
      .then((response) => response.json())
      .then((items) => {
        setItems(items);
      });
  }, []);

  return (
    <div>
      <Head>
        <title>E-Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <center>
          <h1 className="p-3">E-Shop</h1>
        </center>

        <h2>Available Items:</h2>
        <form onSubmit={handleSubmit}>
          <div className="row flex-wrap justify-content-center gap-3">
            {items.map((item) => (
              <Item
                key={item.itemId}
                name={item.itemId}
                picUrl={item.picUrl}
                value={itemBtnValue(item.itemId)}
                color={itemBtnColor(item.itemId)}
                onClick={handleClick(item.itemId)}
              />
            ))}
          </div>
          <div className="checkout-btn d-flex justify-content-center align-items-center">
            <button type="submit" className="btn btn-warning">
              🛒 Checkout
            </button>
          </div>
        </form>
        <div className="checkout-buffer" />
      </main>
    </div>
  );
}
