import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Item from "../components/Item";

export default function Home() {
  const [selectedItems, setSelectedItems] = useState([]);
  const [items, setItems] = useState([]);

  const isItemSelected = (itemId) => selectedItems.includes(itemId);
  const selectItem = (itemId) => {
    return [...selectedItems, itemId];
  };
  const deselectItem = (itemId) => {
    return selectedItems.filter((x) => x !== itemId);
  };
  const handleChange = (itemId) => (event) => {
    if (isItemSelected(itemId)) {
      setSelectedItems(deselectItem(itemId));
      return;
    }

    setSelectedItems(selectItem(itemId));
  };
  const handleSubmit = (event) => {
    event.preventDefault();

    const requestOptions = {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(selectedItems),
    };
    fetch("/api/checkout", requestOptions)
      .then((response) => response.json())
      .then((res) => console.log(res));
  };

  useEffect(() => {
    fetch("/api/items")
      .then((response) => response.json())
      .then((items) => {
        setItems(items);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>E-Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>E-Shop</h1>
        <h2>Available Items:</h2>
        <form onSubmit={handleSubmit}>
          {items.map((item) => (
            <Item
              key={item}
              name={item}
              isChecked={isItemSelected(item)}
              onChange={handleChange(item)}
            />
          ))}
          <button type="submit">Checkout</button>
        </form>
      </main>
    </div>
  );
}
